
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  selector:
    matchLabels:
      app: deploy-web
  replicas: 3    
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: deploy-web
        image: dandaeki/tomcat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: deploy-web
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
